### ISSUE TITLE
Customize Section Missing

### ISSUE THREAD

**Issue by mktgessentials** [joshuaiz/plate#22]
Hello,
For some reason, the customize section is showing up blank. Can someone please help me troubleshoot this issue? There is not a plugin conflict and I have contacted my host and they said its theme-specific. 
![Screen Shot 2020-03-04 at 8 46 05 AM](https://user-images.githubusercontent.com/41482960/75887800-56567280-5df8-11ea-8fbf-a84db3a78cf8.png)

**Comment by joshuaiz** [comment]
Hello...are there any js errors on the page in Chrome Dev Tools?

**Comment by mktgessentials** [comment]
Yes, This is displaying 
![Screen Shot 2020-03-04 at 10 44 25 AM](https://user-images.githubusercontent.com/41482960/75896516-337e8b00-5e05-11ea-89a2-7317325b8f6a.png)

**Comment by joshuaiz** [comment]
What version of PHP are you running and what WP version?

**Comment by mktgessentials** [comment]
PHP Version: 7.3
Wordpress 5.3.2

**Comment by joshuaiz** [comment]
Thanks for that. Let me try to replicate when I have some time tonight. Let me know if you find anything in the meantime.

**Comment by mktgessentials** [comment]
I appreciate that. Its almost as if something is missing that is sending the information to the customize section.

**Comment by mktgessentials** [comment]
Any luck?

**Comment by joshuaiz** [comment]
Hey @mktgessentials sorry my real job had a deadline so was working until late and just crashed after. I'll take a look tonight - thanks for your patience.

**Comment by joshuaiz** [comment]
Hi @mktgessentials I'm not seeing that same error and I'm able to load the Customizer fine using WP 5.3.2/PHP 7.3X so that is pointing to something on your end.

Can you try disabling all plugins and check if you are you loading any external scripts? 

For example, where is `backbone.min.js` coming from? I'm not loading that on my install so that seems to be what is interfering.

<img width="1066" alt="Screen Shot 2020-03-05 at 8 35 37 PM" src="https://user-images.githubusercontent.com/1096738/76044973-851c3800-5f21-11ea-8489-632c9c21b7d4.png">

**Comment by mktgessentials** [comment]
I have disabled all of the plugins and the customizer section will not load. I also disabled the theme and activated 'Twenty Twenty'  and the customizer is displaying for that theme with all of the same plugins enabled.

The backbone.min.js is located in /wp-includes/js/backbone.min.js

**Comment by joshuaiz** [comment]
Interesting. I'll take another look this evening. Def want to get this sorted for you.

**Comment by mktgessentials** [comment]
I appreciate any help you can provide. I am spinning my wheels here.

**Comment by joshuaiz** [comment]
Hey @mktgessentials just to rule out things were only working on my local install, I just uploaded a WordPress install v5.3.2 + PHP 7.3 to a subdomain on DreamHost and still having no issues with the Customizer.

I have no js or PHP errors on the front or back end.

To investigate further, I downloaded WordPress and looked to see where/if it was calling `backbone.min.js` and it is not called or enqueued anywhere in the theme or by WP core that I could find. Not backbone.js would be the cause of this but it's the only thing I can point to in the errors you submitted.

My suggestions from here are the following:

1. Reinstall WordPress 5.3.2 and see if that does anything. I'd try both installing over the top from the admin and then doing a complete fresh install.

2. Download the last **release** of Plate (1.4.0): https://github.com/joshuaiz/plate/releases and see if that version works.

3. Alternatively, download the latest from the Master branch (if that's not the version you're currently using). There's been some more recent updates.

4. Disable any browser extensions.

5. Try commenting out the Modernizr enqueue in Plate's `functions.php`. There were some issues with a couple outdated things included in Modernizr so that might be the culprit. Using Plate from the Master branch has a more updated Modernizr build.

6. Make sure you didn't add any functions or scripts to the theme

I definitely want to get this sorted out however if I can't reproduce the issue we'll have to find another way to isolate the problem. Hopefully one or some of my suggestions will help!

Let me know what you find!
